# shift report generator
# takes all the json data files from a session and makes a nice HTML report
# open the html file in any browser to see it

import json, os, time
from datetime import datetime

# --- load data from various scripts ---
# these files are created by the other scripts when you run them

def load_json(path, default=[]):
    """try to load a json file, return default if it doesnt exist"""
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    print(f"Warning: Could not find {path}, using default.")
    return default

# find the data directory relative to this script
script_dir = os.path.dirname(os.path.abspath(__file__))
data_dir = os.path.join(script_dir, "..", "data")

cycles = load_json(os.path.join(data_dir, "cycles.json"), [])
idles = load_json(os.path.join(data_dir, "idle.json"), [])
walk = load_json(os.path.join(data_dir, "walk_positions.json"), {"walk_m": 0})
events = load_json(os.path.join(data_dir, "events.json"), [])
violations = load_json(os.path.join(data_dir, "ergo_violations.json"), [])
near_misses = load_json(os.path.join(data_dir, "near_misses.json"), [])
queue_events = load_json(os.path.join(data_dir, "queue_events.json"), [])
sop = load_json(os.path.join(data_dir, "sop_result.json"), {"drift_pct": 0})

# calculate stats
num_cycles = len(cycles)
avg_cycle = sum(c.get("dur", 0) for c in cycles) / max(num_cycles, 1)
total_idle = sum(e.get("end_time", 0) - e.get("start_time", 0) for e in idles)
total_walk = walk.get("walk_m", 0) if isinstance(walk, dict) else 0
num_violations = len(violations)
num_near_misses = len(near_misses)
num_queues = len(queue_events)
sop_drift = sop.get("drift_pct", 0) if isinstance(sop, dict) else 0

now = datetime.now()

# --- build the HTML ---
html = f"""<!DOCTYPE html>
<html>
<head>
<title>LineLens AI Shift Report</title>
<style>
body {{ font-family: Arial, sans-serif; background: #1a1a2e; color: #eee; padding: 20px; }}
h1 {{ color: #4ecdc4; text-align: center; }}
.meta {{ text-align: center; color: #888; margin-bottom: 30px; }}
.grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 30px; }}
.card {{ background: #16213e; border-radius: 10px; padding: 20px; text-align: center; }}
.card .number {{ font-size: 2em; font-weight: bold; margin: 10px 0; }}
.card .label {{ color: #888; font-size: 0.9em; }}
.green {{ color: #4ecdc4; }}
.yellow {{ color: #ffd93d; }}
.red {{ color: #ff6b6b; }}
.section {{ background: #16213e; border-radius: 10px; padding: 20px; margin-bottom: 20px; }}
.section h2 {{ color: #4ecdc4; margin-bottom: 10px; }}
.fix {{ background: #0f3460; border-left: 3px solid #ffd93d; padding: 15px; margin: 10px 0; border-radius: 5px; }}
</style>
</head>
<body>

<h1>LineLens AI - Shift Report</h1>
<div class="meta">{now.strftime('%B %d, %Y - %H:%M')}</div>

<div class="grid">
    <div class="card">
        <div class="label">Total Cycles</div>
        <div class="number green">{num_cycles}</div>
    </div>
    <div class="card">
        <div class="label">Avg Cycle Time</div>
        <div class="number">{avg_cycle:.1f}s</div>
    </div>
    <div class="card">
        <div class="label">Idle Time</div>
        <div class="number yellow">{total_idle:.0f}s</div>
    </div>
    <div class="card">
        <div class="label">Walk Distance</div>
        <div class="number">{total_walk:.1f}m</div>
    </div>
    <div class="card">
        <div class="label">Ergo Violations</div>
        <div class="number {'red' if num_violations > 5 else 'yellow'}">{num_violations}</div>
    </div>
    <div class="card">
        <div class="label">Near Misses</div>
        <div class="number red">{num_near_misses}</div>
    </div>
    <div class="card">
        <div class="label">Queue Events</div>
        <div class="number yellow">{num_queues}</div>
    </div>
    <div class="card">
        <div class="label">SOP Drift</div>
        <div class="number {'red' if sop_drift > 20 else 'green'}">{sop_drift:.0f}%</div>
    </div>
</div>

<div class="section">
    <h2>Top 3 Process Fixes</h2>
"""

# auto generate top 3 fixes based on the data
fixes = []
#add a llm call here

# sort by impact and take top 3
fixes.sort(key=lambda x: len(x[2]), reverse=True)
for i, (title, desc, impact) in enumerate(fixes[:3]):
    html += f"""
    <div class="fix">
        <h3>#{i+1}: {title}</h3>
        <p>{desc}</p>
        <p style="color: #ff6b6b; font-weight: bold;">Impact: {impact}</p>
    </div>"""

html += """
</div>
<div style="text-align:center; color:#555; margin-top:30px; font-size:0.8em;">
Generated by LineLens AI
</div>
</body></html>"""

# save the report in the current working directory
fname = f"shift_report_{now.strftime('%Y%m%d_%H%M')}.html"
with open(fname, "w") as f:
    f.write(html)
print(f"\nReport saved: {fname}")
print("Open it in a browser to see it")
